INFO:uvicorn.error:Started server process [201747]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [201747]
INFO:uvicorn.error:Started server process [202358]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Finished server process [202358]
INFO:uvicorn.error:ASGI 'lifespan' protocol appears unsupported.
INFO:uvicorn.error:Started server process [218382]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [218382]
INFO:uvicorn.error:Started server process [219522]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [219522]
INFO:uvicorn.error:Started server process [219575]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Finished server process [219575]
INFO:uvicorn.error:ASGI 'lifespan' protocol appears unsupported.
INFO:uvicorn.error:Started server process [219609]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/up1n99u/IdeaProjects/MLCapstone/./app/main.py", line 40, in main
    return FileResponse(some_file_path)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/responses.py", line 247, in __init__
    assert aiofiles is not None, "'aiofiles' must be installed to use FileResponse"
AssertionError: 'aiofiles' must be installed to use FileResponse
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Finished server process [219609]
INFO:uvicorn.error:ASGI 'lifespan' protocol appears unsupported.
INFO:uvicorn.error:Started server process [219804]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/up1n99u/IdeaProjects/MLCapstone/./app/main.py", line 40, in main
    return FileResponse(some_file_path)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/responses.py", line 247, in __init__
    assert aiofiles is not None, "'aiofiles' must be installed to use FileResponse"
AssertionError: 'aiofiles' must be installed to use FileResponse
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Finished server process [219804]
INFO:uvicorn.error:ASGI 'lifespan' protocol appears unsupported.
INFO:uvicorn.error:Started server process [220518]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 55, in app
    await response(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/responses.py", line 286, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path large-video-file.mp4 does not exist.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [220518]
INFO:uvicorn.error:Started server process [220668]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Finished server process [220668]
INFO:uvicorn.error:ASGI 'lifespan' protocol appears unsupported.
INFO:uvicorn.error:Started server process [220683]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/up1n99u/IdeaProjects/MLCapstone/./app/main.py", line 38, in main
    return FileResponse(some_file_path)
NameError: name 'some_file_path' is not defined
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [220683]
INFO:uvicorn.error:Started server process [220841]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [220841]
INFO:uvicorn.error:Started server process [222017]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [222017]
INFO:uvicorn.error:Started server process [222813]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [222813]
INFO:uvicorn.error:Started server process [222856]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [222856]
INFO:uvicorn.error:Started server process [222926]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:120]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[122:134]
DEBUG:multipart.multipart:Calling on_header_value with data[136:144]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[148:6767]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/up1n99u/IdeaProjects/MLCapstone/./app/main.py", line 52, in create_upload_file
    print(pd.read_csv(file.file, sep='\t'))
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/common.py", line 716, in get_handle
    handle = TextIOWrapper(
AttributeError: 'SpooledTemporaryFile' object has no attribute 'readable'
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:120]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[122:134]
DEBUG:multipart.multipart:Calling on_header_value with data[136:144]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[148:6767]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/up1n99u/IdeaProjects/MLCapstone/./app/main.py", line 52, in create_upload_file
    print(pd.read_csv(file.file, sep='\t'))
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/common.py", line 716, in get_handle
    handle = TextIOWrapper(
AttributeError: 'SpooledTemporaryFile' object has no attribute 'readable'
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:120]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[122:134]
DEBUG:multipart.multipart:Calling on_header_value with data[136:144]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[148:6767]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/up1n99u/IdeaProjects/MLCapstone/./app/main.py", line 52, in create_upload_file
    print(pd.read_csv(file.file, sep='\t'))
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/pandas/io/common.py", line 716, in get_handle
    handle = TextIOWrapper(
AttributeError: 'SpooledTemporaryFile' object has no attribute 'readable'
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [222926]
INFO:uvicorn.error:Started server process [223277]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:120]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[122:134]
DEBUG:multipart.multipart:Calling on_header_value with data[136:144]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[148:6767]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/home/up1n99u/miniconda3/envs/MLCapstone/lib/python3.8/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/up1n99u/IdeaProjects/MLCapstone/./app/main.py", line 52, in create_upload_file
    print(pd.read_csv(StringIO(str(file.file.read(), 'utf-16')), encoding='utf-16'))
UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x30 in position 6618: truncated data
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [223277]
INFO:uvicorn.error:Started server process [223850]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:120]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[122:134]
DEBUG:multipart.multipart:Calling on_header_value with data[136:144]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[148:6767]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:113]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[115:127]
DEBUG:multipart.multipart:Calling on_header_value with data[129:137]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[141:11208]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [223850]
INFO:uvicorn.error:Started server process [224167]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:113]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[115:127]
DEBUG:multipart.multipart:Calling on_header_value with data[129:137]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[141:11208]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [224167]
INFO:uvicorn.error:Started server process [224348]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:multipart.multipart:Calling on_part_begin with no data
DEBUG:multipart.multipart:Calling on_header_field with data[42:61]
DEBUG:multipart.multipart:Calling on_header_value with data[63:113]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_header_field with data[115:127]
DEBUG:multipart.multipart:Calling on_header_value with data[129:137]
DEBUG:multipart.multipart:Calling on_header_end with no data
DEBUG:multipart.multipart:Calling on_headers_finished with no data
DEBUG:multipart.multipart:Calling on_part_data with data[141:11208]
DEBUG:multipart.multipart:Calling on_part_end with no data
DEBUG:multipart.multipart:Calling on_end with no data
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [224348]
INFO:uvicorn.error:Started server process [224647]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [224647]
INFO:uvicorn.error:Started server process [224699]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Finished server process [224699]
INFO:uvicorn.error:ASGI 'lifespan' protocol appears unsupported.
